#!/usr/local/bin/python3.7

print("Let the fun begin")
import urllib.request
import urllib.parse
import json
from bs4 import BeautifulSoup
import requests
from urllib.request import urlopen
import re
import time
import pyperclip

def Trans_normal_W():
  print(soup.find('div',{'id':'phrsListTab'}).find('ul').get_text())
  try:
    soup.find_all('span',{'class':'phonetic'})[-1].get_text()
  except:
    print("[]")

def Trans_S(Words):
  print(soup.find('div',{'id':'phrsListTab'}).find('ul').get_text())

def Trans(Words):
  U_1="http://www.youdao.com/w/eng/"
  U_2="/#keyfrom=dict2.index"
  url= U_1 + Words + U_2
  html = urlopen(url).read().decode('utf-8')
  soup = BeautifulSoup(html, features='lxml')
  try:
    print(soup.find_all('span',{'class':'phonetic'})[-1].get_text())
    print(soup.find('div',{'id':'phrsListTab'}).find('ul').get_text())
  except:
      print(soup.find('div',{'id':'phrsListTab'}).find('ul').get_text())

def Trans_long(content):
  url='http://fanyi.youdao.com/translate?smartresult=dict&smartresult=rule&sessionFrom=http://fanyi.youdao.com/'
  data = {        #表单数据
              'i': content,
              'from': 'AUTO',
              'to': 'AUTO',
              'smartresult': 'dict',
              'client': 'fanyideskweb',
              'doctype': 'json',
              'version': '2.1',
              'keyfrom': 'fanyi.web',
              'action': 'FY_BY_CLICKBUTTION',
              'typoResult': 'false'
          }
  data=urllib.parse.urlencode(data).encode('utf-8')
  response=urllib.request.urlopen(url,data)
  html=response.read().decode('utf-8')
  target=json.loads(html)
  for i in range(len(target['translateResult'][0])):
    print(target['translateResult'][0][i]['tgt'])

A = pyperclip.paste()
while 1 < 2 :
    time.sleep(0.2)
    B = pyperclip.paste()
    if A != B:
        A = B
        print(B)
        try:
          Trans(B)
        except:
          try:
            Trans_long(B)
          except:
            Trans_long(B)
